#program to generate marksheet of a student's.
name=input("name: ")
department=input("Department: ")
year=input("Year: ")
semester=input("Semester: ")
section=input("Section: ")
roll_no=int(input("Roll no: "))
sub1=float(input("Subject 1 marks: "))
sub2=float(input("Subject 2 marks: "))  
sub3=float(input("Subject 3 marks: "))
sub4=float(input("Subject 4 marks: "))
sub5=float(input("Subject 5 marks: "))
print("STUDENT MARKSHEET")
print("Name:",name)
print("Department:",department) 
print("Year:",year)
print("Semester:",semester)
print("Section:",section)
print("Roll no:",roll_no)
print("Subject 1 marks:",sub1)
print("Subject 2 marks:",sub2)
print("Subject 3 marks:",sub3)
print("Subject 4 marks:",sub4)
print("Subject 5 marks:",sub5)
total_marks=sub1+sub2+sub3+sub4+sub5
per=(total_marks/500)*100
print("Total marks:",total_marks)
print(f"Percentage:{per: .2f}%")